
esphome:
  name: "apollo-cast-1-eth"
  friendly_name: Apollo CAST-1
  comment: Apollo CAST-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.CAST-1-ETH"
    version: ${version}

  min_version: 2026.6.0

  on_boot:
    - priority: 800
      then:
        - if:
            condition:
              - lambda: "return id(runTest);"
            then:
              - lambda: "id(testScript).execute();"
    - priority: 500
      then:
        - text_sensor.template.publish:
            id: apollo_firmware_version
            state: "${version}"

dashboard_import:
  package_import_url: github://ApolloAutomation/CAST-1/Integrations/ESPHome/CAST-1_ETH.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://apolloautomation.github.io/CAST-1/firmware-e/manifest.json

logger:

ethernet:
  type: W5500
  clk_pin: GPIO41
  mosi_pin: GPIO40
  miso_pin: GPIO35
  cs_pin: GPIO42
  interrupt_pin: GPIO2
  reset_pin: GPIO36

select:
  - platform: template
    id: firmware_selector
    name: Firmware Type
    icon: "mdi:test-tube"
    entity_category: config
    optimistic: true
    restore_value: true
    options:
      - "WiFi"
      - "Ethernet"
    initial_option: "Ethernet"
    on_value:
      then:
        - if:
            condition:
              lambda: 'return id(firmware_selector).current_option() == "Ethernet";'
            then:
              - logger.log: "OTA updates set to use ethernet firmware"
              - lambda: id(update_http_request).set_source_url("https://apolloautomation.github.io/CAST-1/firmware-e/manifest.json");
              - component.update: update_http_request
            else:
              - logger.log: "OTA updates set to use wifi firmware"
              - lambda: id(update_http_request).set_source_url("https://apolloautomation.github.io/CAST-1/firmware-w/manifest.json");
              - component.update: update_http_request

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "IP Address"
      id: eth_ip
      entity_category: "diagnostic"

packages:
  core: !include Core.yaml
